### PR TITLE
latest beta linking

### PR DESCRIPTION
**Pull request by VirisOnGithub**

### CODE REVIEW

**Comment by flashonfire** [comment]
Would you mind using GitHub's powerful permalinks to link to the files instead of doing an MR every single time there's an update ?

You can use this link to grab a specific file from the latest onyx release
https://github.com/onyx-lyon1/onyx/releases/latest/download/filename

I saw the filenames are not the same every time (cc @hatch01), so you may use the GitHub API to make a more robust download button

https://api.github.com/repos/onyx-lyon1/onyx/releases/latest : this link grabs all the content of the latest onyx release in a convenient JSON format, for example

I don't have time to check for pre releases versions, but I bet there are similar options for them.

We are not cave men to update links every single time we push a new release

**Comment by hatch01** [comment]
Or Just link to the release page, then the user can download the version he wants based on the processor he has.

**Comment by hatch01** [comment]
@VirisOnGithub are you ok with my modification ?

**Comment by VirisOnGithub** [comment]
> https://api.github.com/repos/onyx-lyon1/onyx/releases/latest : this link grabs all the content of the latest onyx release in a convenient JSON format, for example
I just updated the link, there's nothing bad here, it's not as if it was the biggest site in the entire world.
Nevertheless, I will look for the api to link dynamically

@hatch01 I think it's better to have a direct link on the site for people that don't know github.

I will look further, but your modifications seem okay to me

**Comment by VirisOnGithub** [comment]
I explored the darker sides of the GitHub API to find those ...

**Comment by uku3lig** [comment]
oui bon "dark side" faut pas pousser mamie dans les orties non plus hein

**Comment by hatch01** [comment]
image
hmmm ?

**Comment by VirisOnGithub** [comment]
Works on my pc

**Comment by VirisOnGithub** [comment]
Well at the same time, you can't even load the JS bundles, so ig this is an internet issue

**Pull request merged**
